<?php
/**
 * @file
 * Pivot Paragraphs module file based on Bootstrap Paragraphs.
 */

/**
 * Implements hook_theme().
 */
function pivot_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__default' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__pp_accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__pp_carousel' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__pp_tabs' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__pp_columns_three_uneven' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__pp_columns_two_uneven' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__pp_image' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__pp_modal' => [
      'base hook' => 'paragraph',
    ],
    'field__entity_reference_revisions' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__pp_column_content' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__pp_column_content_2' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__pp_column_content_3' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__pp_image__image' => [
      'base hook' => 'paragraph',
    ],
  ];
}
